---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.15.0'
- 'pip install cfn-lint==0.21.5'
script:
- 'yamllint module.yml && yamllint test/*.yml'
- 'cfn-lint -t module.yml && cfn-lint -t test/*.yml'
- 'grep -q "LICENSE-2.0" module.yml'
